name: "Python Package Index Generator"
description: "Generates an index.html file for hosting a private Python package repository"
author: "EarningsCall"

inputs:
  s3_bucket_name:
    description: "S3 bucket name"
    required: true
    default: "EarningsCall"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install boto3 botocore

    - name: Generate Index
      shell: bash
      run: |
        python ${{ github.action_path }}/generat-index.py --s3-bucket-name ${{ inputs.s3_bucket_name }}

branding:
  icon: "package"
  color: "blue"
